### PR TITLE
Add support for BuildHostApplicationBuilder

### PR DESCRIPTION
**Pull request by gilmar-sales**
Support for BuildHost with the HostApplicationBuilder:

```csharp
 public class Startup
{
        // with
        public void ConfigureHostApplicationBuilder(IHostApplicationBuilder hostApplicationBuilder)
        {
            // do something here...
        }

        // will be able to
        public IHost BuildHostApplicationBuilder(HostApplicationBuilder hostApplicationBuilder)
        {
            var hostApplication = hostApplicationBuilder.Build();
            // do something here...
            return hostApplication;
        }
}
```

### CODE REVIEW

**Comment by WeihanLi** [comment]
Could it be configured in the `Configure` method? We could inject any service registered in the service collection like `IServiceProvider`

https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/d55ca649090492565a5f2ec088898370dd030724/test/Xunit.DependencyInjection.Test/HostApplicationBuilderTest.cs#L35

**Comment by gilmar-sales** [comment]
**Configure** method doesn't allow access to the IHost instance like the **BuildHost** method for the **CreateHostBuilder**, this could help if thirdparty libraries uses the **IHost** instead of the **IServiceProvider**

**Comment by WeihanLi** [comment]
what about supporting `IHost` in the `Configure` method?

**Comment by pengweiqhca** [comment]
``` C#
public void Configure(IHost host)
{
}
```
image

**Pull request merged**
